### ISSUE TITLE
Image.load

### ISSUE THREAD

**Issue by Hejle** [IgorTimofeev/Image#2]
I have tried to get image.load to work, but I am unsure of how. I tried to use image.create to make sure the image should be compatible with image.load.

```lua
local image = require("image")
local GUI = require("GUI")

local mainContainer = GUI.fullScreenContainer()

image.save("/test/img.pic", image.create(128, 128, 0x000040, 0x000040, a, x, 4), nil)
img = image.load("img.pic")

print(img)

--------------------------------------------------------------------------------

mainContainer:addChild(GUI.panel(1, 1, mainContainer.width, mainContainer.height, 0x2D2D2D))

-- Load image, create widget from it and add it to main container
mainContainer:addChild(GUI.image(2, 2, img))

mainContainer:drawOnScreen(true)
mainContainer:startEventHandling()
```

When I run this I see that it creates an image in my directory and prints false.
After that I get an error. I suspect its either because I don't create the image correctly or the image.load function doesn't work, but I am not sure.

Maybe I do something else wrongly.. :)

![billede](https://user-images.githubusercontent.com/18572997/44517527-41a80300-a6c8-11e8-8f41-71dba9a1ae45.png)
Image of the error I get

**Comment by IgorTimofeev** [comment]
You're saving created image to **/test/img.pic**, but loading it from **img.pic**. Why are you using different paths? For such mistakes there is a tip: 

```lua
local result, reason = image.load(path)
```

If loaded **result** equals **false** then reason variable should contain a reason why image can't be loaded: it can be "file not exists" or something like that
